collaborators:
  mariocj89:
    permission: admin
  dothub-bot:
    permission: admin
hooks:
  web:
    active: true
    config:
      content_type: json
      insecure_ssl: '0'
      url: https://dothub-web.herokuapp.com/github
    events:
    - '*'
labels:
  bug:
    color: ee0701
  duplicate:
    color: cccccc
  enhancement:
    color: 84b6eb
  help wanted:
    color: 128A0C
  invalid:
    color: e6e6e6
  question:
    color: cc317c
  wontfix:
    color: ffffff
options:
  description: "Test sample3"
  has_downloads: true
  has_issues: true
  has_wiki: true
  homepage: null
  name: test
  private: false
